[variables]
NIXPACKS_PYTHON_VERSION = "3.10"

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "cd src && python manage.py collectstatic --noinput",
  "cd src && python manage.py migrate"
]
